### ISSUE TITLE
Error occurs when enabling https on dev in Nuxt3

### ISSUE THREAD

**Issue by shtse8** [unjs/ohmyfetch#120]
```
[nuxt] [request error] [unhandled] [500] fetch failed ()
  at async $fetchRaw2 (/D:/project/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
  at async /D:/project/.nuxt/dev/index.mjs:2411:20
  at async /D:/project/.nuxt/dev/index.mjs:2472:64
  at async /D:/project/.nuxt/dev/index.mjs:135:22
  at async /D:/project/node_modules/h3/dist/index.mjs:492:19
  at async nodeHandler (/D:/project/node_modules/h3/dist/index.mjs:438:7)
  at async ufetch (/D:/project/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (/D:/project/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
  at async Object.errorhandler [as onError] (/D:/project/.nuxt/dev/index.mjs:383:16)
  at async nodeHandler (/D:/project/node_modules/h3/dist/index.mjs:445:9)
```

How can I solve this?

**Comment by cwe-spb** [comment]
same problems.

**Comment by cwe-spb** [comment]
@shtse8 https://github.com/nuxt/framework/discussions/7186#discussioncomment-3635744

**Comment by danielroe** [comment]
Yes, this should be resolved in https://github.com/nuxt/framework/pull/7271. You can use it on the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), but note that if you are using a self-signed certificate you must also set `NODE_TLS_REJECT_UNAUTHORIZED=0`.

If that does not resolve things for you, please raise a new issue in https://github.com/nuxt/framework. 🙏
